version: 2
jobs:
  terraform_plan:
    docker:
    - image: circleci/python:3.6.1
    environment:
    - AWS_DEFAULT_OUTPUT: json
    - TERRAFORM_VERSION: 0.12.10
    steps:
    - checkout
    - run:
        name: Setup AWS CLI
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip3 install -r awscli
workflows:
  version: 2
  aws-cli:
    jobs:
    - terraform_plan:
        context: aws
