version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair/default
    steps:
    - checkout
    - setup_remote_docker:
        version: 17.11.0-ce
    - run: |
        docker pull nginx/nginx:latest
        echo $(docker image inspect --format="{{index .RepoDigests 0}}" nginx/nginx:latest) > /image.txt
    - clair/scan:
        image_file: /image.txt

workflows:
  test:
    jobs:
    - scan_images
