 version: 2.1
 
 orbs:
   clair: ovotech/clair-scanner@1
   aws-cli: circleci/aws-cli@0.1.22

 
 jobs:
   scan_ecr:
     executor: clair/default
     steps:
     - run: $(aws ecr get-login --no-include-email)
     - clair/scan:
         image: 221056883232.dkr.ecr.us-west-2.amazonaws.com/nginx-website:clairtestng
 workflows:
   test:
     jobs:
       - scan_ecr
     context: aws
