version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "aws cli setup is done"
  aws-cli-PROD:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
      - run: echo "aws cli setUP IN PROD"    
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
      - aws-cli-PROD:
          context: production
        
