version: 2.1

orbs:
  clair_scanner: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair_scanner/default
    steps:
    - checkout
    -run: |
        docker build -t clairtest .
        
    - clair_scanner/scan:
        image: clairtest

workflows:
  test:
    jobs:
      - scan_images
