version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_ecr:
    executor: clair/default
    steps:
    - run: $(aws ecr get-login --region ap-southeast-2 --no-include-email)
    - clair/scan:
        image: 221056883232.dkr.ecr.ap-southeast-2.amazonaws.com/docker:tomcatv1
workflows:
  test:
    jobs:
    - scan_ecr  
 
