version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair/default
    steps:
    - run: |
         cat > Dockerfile <<- "EOF"
         FROM alpine:3.4

        RUN apk update && \
        apk add curl && \
        apk add git && \
        apk add vim
        EOF
        docker build -t alpine/clair .
        docker push alpine/clair
    - clair/scan:
        image: 

workflows:
  test:
    jobs:
    - scan_images
