version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair/default
    docker:
      #- image:18.06.0-ce-git
      - image: docker:17.05.0-ce-git
    steps:
    - checkout
    - run: |
        docker build -t alpine/clair .
        docker push alpine/clair
    - clair/scan:
        image: 

workflows:
  test:
    jobs:
    - scan_images
