version: 2.1

orbs:
  clair-scanner: ovotech/clair-scanner@1.6.0
  aws-ecr: circleci/aws-ecr@6.7.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: myContext
          create-repo: true
          dockerfile: myDockerfile
          path: pathToMyDockerfile
          profile-name: myProfileName
          region: AWS_REGION_ENV_VAR_NAME
          repo: myECRRepository
          tag: 'latest,myECRRepoTag'
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:stretch
