version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair/default
   - setup_remote_docker:
    steps:
    - checkout
    - run: |
        docker build -t alpine/clair .
        docker push alpine/clair
    - clair/scan:
        image: 

workflows:
  test:
    jobs:
    - scan_images
