version: 2.1
orbs:
  clair-scanner: ovotech/clair-scanner@1.6.0
jobs:
  scan_images:
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:stretch
workflows:
  test:
    jobs:
      - scan_images        
