version: 2.1

references:

setup_terraform: &setup_terraform
    run:
      name: Setup Terraform
      command: |
        curl -O https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_linux_amd64.zip
        curl -O https://releases.hashicorp.com/terraform/0.12.10/terraform_0.12.10_SHA256SUMS
        terraform_sha256_sum=$(cat terraform_0.12.10_SHA256SUMS | grep linux_amd64)
        echo $terraform_sha256_sum
        terraform_sha256_sum_calculated=$(sha256sum terraform_0.12.10_linux_amd64.zip)
        echo $terraform_sha256_sum_calculated
        echo "Checking Terraform checksums ..."
        grep $terraform_sha256_sum_calculated terraform_0.12.10_SHA256SUMS
        unzip terraform_0.12.10_linux_amd64.zip -d terraform
        echo 'export PATH=$CIRCLE_WORKING_DIRECTORY/terraform:$PATH' >> $BASH_ENV
setup_awscli: &setup_awscli
  run:
    name: Setup AWS CLI
    command: |
      python3 -m venv venv
      . venv/bin/activate
      pip3 install -r requirements.txt
      
jobs:
  terraform_plan:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
      TERRAFORM_VERSION: 0.12.10
    steps:
      - checkout
      - *setup_awscli
    context: aws  
workflows:
  version: 2.1
  aws-cli:
    jobs:
    - terraform_plan:
        context: aws
