version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
references: 
setup_terraform: &setup_terraform
  run:
    name: Setup Terraform
    command: |
      curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS
      terraform_sha256_sum=$(cat terraform_${TERRAFORM_VERSION}_SHA256SUMS | grep linux_amd64)
      echo $terraform_sha256_sum
      terraform_sha256_sum_calculated=$(sha256sum terraform_${TERRAFORM_VERSION}_linux_amd64.zip)
      echo $terraform_sha256_sum_calculated
      echo "Checking Terraform checksums ..."
      grep $terraform_sha256_sum_calculated terraform_${TERRAFORM_VERSION}_SHA256SUMS
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d terraform
      echo 'export PATH=$CIRCLE_WORKING_DIRECTORY/terraform:$PATH' >> $BASH_ENV
terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      source $BASH_ENV
      cd environments/<< parameters.TERRAFORM_ENVIRONMENT >>
      terraform init    


aws-cli-example: &aws-cli-example
  executor: aws-cli/default
  steps:
    - checkout
    - aws-cli/setup:
        profile-name: example
    - run: echo "aws cli setup is done"

jobs:
  terraform_plan:
    parameters:
      TERRAFORM_ENVIRONMENT:
        type: env_var_name
        default: sandbox
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
      TERRAFORM_VERSION: 0.12.10
    steps:
      - checkout
      - *setup_terraform
      - *aws-cli-example
      - *terraform_init


workflows:
  version: 2
  aws-cli:
    jobs:
      - terraform_plan:
          context: aws
        
