version: 2.1

orbs:
  clair-scanner: ovotech/clair-scanner@1.6.0

jobs:
  scan_images:
    executor: clair/default
    steps:
    - run: |
        docker pull nginx:latest
        echo $(docker image inspect --format="{{index .RepoDigests 0}}" nginx:latest) > /image.txt
    - clair/scan:
        image_file: /image.txt

workflows:
  test:
    jobs:
    - scan_images
