version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_images:
    executor: clair/default
    steps:
    - clair/scan:
        image: alpine/clair
        - run: |
            docker build -t alpine/clair .

workflows:
  test:
    jobs:
    - scan_images
