version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
references: 
aws-cli-example: &aws-cli-example
  executor: aws-cli/default
  steps:
    - checkout
    - aws-cli/setup:
        profile-name: example
    - run: echo "aws cli setup is done"

jobs:
  terraform_plan:
    parameters:
      TERRAFORM_ENVIRONMENT:
        type: env_var_name
        default: sandbox
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
      TERRAFORM_VERSION: 0.12.10
    steps:
      - checkout
      - *setup_terraform
      - restore_cache:
          key: v1-{{ checksum "requirements.txt" }}
      - *aws-cli-example
      - save_cache:
          key: v1-{{ checksum "requirements.txt" }}
          paths:
          - venv
      - *terraform_init
      - *terraform_plan


workflows:
  version: 2
  aws-cli:
    jobs:
      - terraform_plan:
          context: aws
        
