version: 2.1

jobs:
build_n_push:
    parameters:
      IMAGE_TAG:
        type: string
        default: latest
      AWS_DEFAULT_REGION:
        type: string
        default: us-east-1
    docker:
      - image: circleci/python:3.6.1
        environment:
          AWS_DEFAULT_OUTPUT: json
    steps:
      - run:
          name: Build image
          command: |
            docker build -t testclair .
workflows:
  build:
    jobs:
      - build_n_push:
          IMAGE_TAG: sandbox
          AWS_DEFAULT_REGION: us-east-1
     
