####test#######
version: 2.1

orbs:
  clair: ovotech/clair-scanner@1

jobs:
  scan_ecr:
    executor: clair/default
    steps:
    - run: $(aws ecr get-login --region us-west-2 --no-include-email)
    - clair/scan:
        image: 848446468820.dkr.ecr.us-west-2.amazonaws.com/clairtest:latest
workflows:
  test:
    jobs:
    - scan_ecr
